name: Auto Deployment
run-name: Automatically deploying to server...

on:
    push:
        branches: [master]

jobs:
    autodeploy:
        name: Auto Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: awalsh128/cache-apt-pkgs-action@latest
              with: 
                packages: sshpass
            - name: connect and pull
              run: sshpass -p ${{ secrets.SSH_PASSWORD }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull origin master && pkill waitress-serve && make && exit"