name: Auto Deployment
run-name: Automatically deploying to server...

on:
    push:
        branches: [master]

jobs:
    autodeploy:
        name: Auto Deploy
        runs-on: ubuntu-latest
        steps:
            - name: install ssh keys
              run: |
                install -m 600 -D /dev/null ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            - name: connect and pull
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} &&git pull origin master && pkill waitress-serve && make && exit"
            - name: cleanup
              run: rm -rf ~/.ssh